import type { Rating } from "../components/ratingsComp";
import ProfilePic from '../../../../assets/images/profilePic.png'



export const tabSlides: Rating[] = [
  {
    title: "Tradie/Freelancer",
    subtitle: "Kitchen attachments installation",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Patio Renovation – Tracked milestones and site updates",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Client",
    subtitle: "Looking for kitchen fittings jhijhihfioj iofjaio aifj weafo afffae aefef ioj",
    image: ProfilePic,
    rating: 4.5,
    price: 100,
  },
  {
    title: "Client",
    subtitle: "Small bathroom rework",
    image: ProfilePic,
    rating: 4.8,
    price: 130,
  },
  {
    title: "Enterprise",
    subtitle: "Bulk interior refurbishing",
    image: ProfilePic,
    rating: 5,
    price: 500,
  },
  {
    title: "Enterprise",
    subtitle: "Office floor installation",
    image: ProfilePic,
    rating: 4.9,
    price: 600,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Kitchen attachments installation",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Patio Renovation – Tracked milestones and site updates",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Client",
    subtitle: "Looking for kitchen fittings jhijhihfioj iofjaio aifj weafo afffae aefef ioj",
    image: ProfilePic,
    rating: 4.5,
    price: 100,
  },
  {
    title: "Client",
    subtitle: "Small bathroom rework",
    image: ProfilePic,
    rating: 4.8,
    price: 130,
  },
  {
    title: "Enterprise",
    subtitle: "Bulk interior refurbishing",
    image: ProfilePic,
    rating: 5,
    price: 500,
  },
  {
    title: "Enterprise",
    subtitle: "Office floor installation",
    image: ProfilePic,
    rating: 4.9,
    price: 600,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Kitchen attachments installation",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Patio Renovation – Tracked milestones and site updates",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Client",
    subtitle: "Looking for kitchen fittings jhijhihfioj iofjaio aifj weafo afffae aefef ioj",
    image: ProfilePic,
    rating: 4.5,
    price: 100,
  },
  {
    title: "Client",
    subtitle: "Small bathroom rework",
    image: ProfilePic,
    rating: 4.8,
    price: 130,
  },
  {
    title: "Enterprise",
    subtitle: "Bulk interior refurbishing",
    image: ProfilePic,
    rating: 5,
    price: 500,
  },
  {
    title: "Enterprise",
    subtitle: "Office floor installation",
    image: ProfilePic,
    rating: 4.9,
    price: 600,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Kitchen attachments installation",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Patio Renovation – Tracked milestones and site updates",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Client",
    subtitle: "Looking for kitchen fittings jhijhihfioj iofjaio aifj weafo afffae aefef ioj",
    image: ProfilePic,
    rating: 4.5,
    price: 100,
  },
  {
    title: "Client",
    subtitle: "Small bathroom rework",
    image: ProfilePic,
    rating: 4.8,
    price: 130,
  },
  {
    title: "Enterprise",
    subtitle: "Bulk interior refurbishing",
    image: ProfilePic,
    rating: 5,
    price: 500,
  },
  {
    title: "Enterprise",
    subtitle: "Office floor installation",
    image: ProfilePic,
    rating: 4.9,
    price: 600,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Kitchen attachments installation",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Patio Renovation – Tracked milestones and site updates",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Client",
    subtitle: "Looking for kitchen fittings jhijhihfioj iofjaio aifj weafo afffae aefef ioj",
    image: ProfilePic,
    rating: 4.5,
    price: 100,
  },
  {
    title: "Client",
    subtitle: "Small bathroom rework",
    image: ProfilePic,
    rating: 4.8,
    price: 130,
  },
  {
    title: "Enterprise",
    subtitle: "Bulk interior refurbishing",
    image: ProfilePic,
    rating: 5,
    price: 500,
  },
  {
    title: "Enterprise",
    subtitle: "Office floor installation",
    image: ProfilePic,
    rating: 4.9,
    price: 600,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Kitchen attachments installation",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Tradie/Freelancer",
    subtitle: "Patio Renovation – Tracked milestones and site updates",
    image: ProfilePic,
    rating: 5,
    price: 120,
  },
  {
    title: "Client",
    subtitle: "Looking for kitchen fittings jhijhihfioj iofjaio aifj weafo afffae aefef ioj",
    image: ProfilePic,
    rating: 4.5,
    price: 100,
  },
  {
    title: "Client",
    subtitle: "Small bathroom rework",
    image: ProfilePic,
    rating: 4.8,
    price: 130,
  },
  {
    title: "Enterprise",
    subtitle: "Bulk interior refurbishing",
    image: ProfilePic,
    rating: 5,
    price: 500,
  },
  {
    title: "Enterprise",
    subtitle: "Office floor installation",
    image: ProfilePic,
    rating: 4.9,
    price: 600,
  },
]